#!/bin/sh

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  exit 1
}

altDraw() {
  if [[ $(echo $(pistol "$file")) == *"PERMISSIONS | SIZE | MODIFICATION TIME | FILE NAME"* ]]; then
    pistol "$file"
  else
    bat --color always "$file"
  fi
  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"
filename=${file##*/}
mime=$(mimetype "$file")

case "${mime##*: }" in 
  image/*)
    draw "$file"
    ;;
  audio/*)
    if [[ ! -f "/tmp/${file////_}.txt" || ! -f "/tmp/${file////_}.png" ]]; then
      ffmpeg -i "$file" -an -vcodec copy "/tmp/${file////_}.jpg" -vf scale=400:400 "/tmp/${file////_}.png" >/dev/null 2>&1
      ffmpeg -i "$file" -f ffmetadata "/tmp/${file////_}.txt" >/dev/null 2>&1
    fi
    echo -e '\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
    cat "/tmp/${file////_}.txt"
    draw "/tmp/${file////_}.png"
    ;;
  video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    ;;
  application/x-blender)
    exit 0
    ;;
  application/x-shellscript)
    altDraw
    ;;
  application/*)
    if [[ ! -f "/tmp/${filename%.*}.pdf" || ! -f "/tmp/${file////_}.png" ]]; then
      [[ $(file -Lb --mime-type "$file") != "application/pdf" && $(file -Lb --mime-type "$file") != "application/json" ]] &&
        libreoffice --headless --convert-to pdf "$file" --outdir "/tmp/" >/dev/null 2>&1

      if [[ $(file -Lb --mime-type "$file") == "application/pdf" ]]; then
        pdftoppm -f 1 -l 1 "$file" >> "/tmp/${file////_}.png"
      elif [[ -f "/tmp/${filename%.*}.pdf" ]]; then
        pdftoppm -f 1 -l 1 "/tmp/${filename%.*}.pdf" >> "/tmp/${file////_}.png"
      else
        altDraw
      fi
    fi
    draw "/tmp/${file////_}.png"
    ;;
  *)
    altDraw
esac
