#!/bin/bash

draw() {
  kitten icat --stdin no --transfer-mode memory --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
  [[ $(kitten icat --stdin no --transfer-mode memory "$1" </dev/null) == "" ]] && echo "no preview sorry"

  exit 1
}

altDraw() {
  [[ $(echo $(pistol "$file")) == *"PERMISSIONS | SIZE | MODIFICATION TIME"* ]] && pistol "$file" || bat --color always "$file"

  exit 1
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"
filename=${file##*/}
mime=$(mimetype "$file")

[[ ! ${mime##*: } =~ (video|audio).* ]] && (( $(du -m "$file" | cut -f 1) > 10 )) && echo "file is too big to preview" && exit 1

case "${mime##*: }" in 
  image/*)
    draw "$file"
    ;;
  audio/*)
    if [[ ! -f "/tmp/${file////_}.txt" || ! -f "/tmp/${file////_}.png" ]]; then
      ffmpeg -i "$file" -an -vcodec copy "/tmp/${file////_}.jpg" -vf scale=400:400 "/tmp/${file////_}.png" >/dev/null 2>&1
      ffmpeg -i "$file" -f ffmetadata "/tmp/${file////_}.txt" >/dev/null 2>&1
    fi
    echo -e '\n\n\n\n\n\n\n\n\n\n\n\n\n\n'
    cat "/tmp/${file////_}.txt"
    draw "/tmp/${file////_}.png"
    ;;
  video/*)
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    draw "$(vidthumb "$file")"
    ;;
  application/x-blender)
    echo "no preview sorry"
    ;;
  application/x-shellscript)
    altDraw
    ;;
  application/*)
    if [[ $(cat "file") != "/tmp/${filename%.*}.txt" ]]; then
      echo $(cat "$file") > "/tmp/${filename%.*}.txt" && [[ -f "/tmp/${filename%.*}.pdf" ]] && rm /tmp/${filename%.*}.pdf

      if [[ ! -f "/tmp/${filename%.*}.pdf" || ! -f "/tmp/${file////_}.png" ]]; then
        if [[ ! $(file -Lb --mime-type "$file") =~ (pdf|json).* ]]; then
          timeout 3 libreoffice --headless --convert-to pdf "$file" --outdir "/tmp/" >/dev/null 2>&1
        fi

        if [[ $(file -Lb --mime-type "$file") == "application/pdf" ]]; then
          pdftoppm -f 1 -l 1 "$file" > "/tmp/${file////_}.png"
        elif [[ -f "/tmp/${filename%.*}.pdf" ]]; then
          pdftoppm -f 1 -l 1 "/tmp/${filename%.*}.pdf" > "/tmp/${file////_}.png"
        else
          altDraw
        fi
      fi
    fi

    draw "/tmp/${file////_}.png"
    ;;
  *)
    altDraw
esac
